name: Build mold stable and nightly builds

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILDER_REPOSITORY: ghcr.io/zhongruoyu/mold-nightly/mold-builder
  BUILD_CACHE_REPOSITORY: ghcr.io/zhongruoyu/mold-nightly/mold-builder/cache

jobs:
  prepare:
    name: Prepare build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tag_name: ${{ steps.determine_build_attributes.outputs.tag_name }}
      mold_stable_commit_sha: ${{ steps.determine_build_attributes.outputs.mold_stable_commit_sha }}
      mold_stable_commit_date: ${{ steps.determine_build_attributes.outputs.mold_stable_commit_date }}
      mold_stable_version: ${{ steps.determine_build_attributes.outputs.mold_stable_version }}
      mold_nightly_commit_sha: ${{ steps.determine_build_attributes.outputs.mold_nightly_commit_sha }}
      mold_nightly_commit_date: ${{ steps.determine_build_attributes.outputs.mold_nightly_commit_date }}
      mold_nightly_version: ${{ steps.determine_build_attributes.outputs.mold_nightly_version }}
    steps:
      - name: Determine build attributes
        id: determine_build_attributes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag_name="$(date -u +%Y%m%dT%H%M%SZ)"

          mold_stable_tag="$(gh api /repos/rui314/mold/releases/latest -q .tag_name)"
          mold_stable_commit_info="$(gh api "/repos/rui314/mold/commits/tags/$mold_stable_tag")"
          mold_stable_commit_sha="$(jq --raw-output .sha <<<"$mold_stable_commit_info")"
          mold_stable_commit_date="$(jq --raw-output .commit.committer.date <<<"$mold_stable_commit_info")"
          mold_stable_version="${mold_stable_tag#v}"

          mold_nightly_commit_info="$(gh api /repos/rui314/mold/commits/heads/main)"
          mold_nightly_commit_sha="$(jq --raw-output .sha <<<"$mold_nightly_commit_info")"
          mold_nightly_commit_date="$(jq --raw-output .commit.committer.date <<<"$mold_nightly_commit_info")"
          mold_nightly_version="nightly"

          {
            echo "tag_name=$tag_name"
            echo "mold_stable_commit_sha=$mold_stable_commit_sha"
            echo "mold_stable_commit_date=$mold_stable_commit_date"
            echo "mold_stable_version=$mold_stable_version"
            echo "mold_nightly_commit_sha=$mold_nightly_commit_sha"
            echo "mold_nightly_commit_date=$mold_nightly_commit_date"
            echo "mold_nightly_version=$mold_nightly_version"
          } | tee -a "$GITHUB_OUTPUT"

  mold-builder:
    needs: prepare
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - arm
          - riscv64
          - ppc64le
          - s390x
          - loongarch64
      fail-fast: false
    name: Build mold builder (${{ matrix.arch }})
    runs-on: ${{ contains(fromJSON('["aarch64", "arm"]'), matrix.arch) && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: write
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to GitHub Container Registry
        if: github.ref_name == 'main'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: zhongruoyu
          password: ${{ github.token }}

      - name: Set up build
        id: setup_build
        env:
          PUSH: ${{ github.ref_name == 'main' }}
        run: |
          {
            echo "cache_from=type=registry,ref=$BUILD_CACHE_REPOSITORY:$ARCH"
            if [[ "$PUSH" = true ]]; then
              echo "cache_to=type=registry,ref=$BUILD_CACHE_REPOSITORY:$ARCH,mode=max"
              echo "push=true"
            else
              echo "cache_to="
              echo "push=false"
            fi
          } >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          platforms: linux/${{ env.ARCH }}
          tags: ${{ env.BUILDER_REPOSITORY }}:${{ env.ARCH }}
          file: ${{ env.ARCH }}.Dockerfile
          cache-from: ${{ steps.setup_build.outputs.cache_from }}
          cache-to: ${{ steps.setup_build.outputs.cache_to }}
          push: ${{ steps.setup_build.outputs.push }}

  build:
    needs: [prepare, mold-builder]
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - arm
          - riscv64
          - ppc64le
          - s390x
          - loongarch64
        variant:
          - stable
          - nightly
      fail-fast: false
    name: Build (${{ matrix.arch }} ${{ matrix.variant }})
    runs-on: ${{ contains(fromJSON('["aarch64", "arm"]'), matrix.arch) && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: read
    env:
      ARCH: ${{ matrix.arch }}
      VARIANT: ${{ matrix.variant }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: zhongruoyu
          password: ${{ github.token }}

      - name: Set up build
        id: setup_build
        env:
          MOLD_STABLE_COMMIT_SHA: ${{ needs.prepare.outputs.mold_stable_commit_sha }}
          MOLD_STABLE_COMMIT_DATE: ${{ needs.prepare.outputs.mold_stable_commit_date }}
          MOLD_STABLE_VERSION: ${{ needs.prepare.outputs.mold_stable_version }}
          MOLD_NIGHTLY_COMMIT_SHA: ${{ needs.prepare.outputs.mold_nightly_commit_sha }}
          MOLD_NIGHTLY_COMMIT_DATE: ${{ needs.prepare.outputs.mold_nightly_commit_date }}
          MOLD_NIGHTLY_VERSION: ${{ needs.prepare.outputs.mold_nightly_version }}
        run: |
          case "$VARIANT" in
          stable)
            build_config="mold-$MOLD_STABLE_VERSION-$ARCH-linux"
            mold_commit_sha="$MOLD_STABLE_COMMIT_SHA"
            mold_commit_timestamp="$(date --utc --date="$MOLD_STABLE_COMMIT_DATE" +%s)"
            ;;
          nightly)
            build_config="mold-$MOLD_NIGHTLY_VERSION-$ARCH-linux"
            mold_commit_sha="$MOLD_NIGHTLY_COMMIT_SHA"
            mold_commit_timestamp="$(date --utc --date="$MOLD_NIGHTLY_COMMIT_DATE" +%s)"
            ;;
          esac

          {
            echo "build_config=$build_config"
            echo "mold_commit_sha=$mold_commit_sha"
            echo "mold_commit_timestamp=$mold_commit_timestamp"
          } | tee -a "$GITHUB_OUTPUT"

      - name: Checkout mold
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: rui314/mold
          ref: ${{ steps.setup_build.outputs.mold_commit_sha }}
          path: mold
          persist-credentials: false

      - name: Build mold
        id: build_mold
        env:
          BUILD_CONFIG: ${{ steps.setup_build.outputs.build_config }}
          MOLD_COMMIT_TIMESTAMP: ${{ steps.setup_build.outputs.mold_commit_timestamp }}
          SETARCH_COMMAND: ${{ matrix.arch == 'arm' && 'setarch linux32' || '' }}
        run: |
          docker run \
            --rm \
            --platform="linux/$ARCH" \
            --mount="type=bind,src=$PWD/mold,dst=/usr/local/src/mold" \
            --mount="type=bind,src=$PWD/build-mold.sh,dst=/usr/local/src/mold/build-mold.sh" \
            --workdir="/usr/local/src/mold" \
            "$BUILDER_REPOSITORY:$ARCH" \
            $SETARCH_COMMAND ./build-mold.sh "$BUILD_CONFIG" "$MOLD_COMMIT_TIMESTAMP"

      - name: Upload build output
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: ${{ steps.setup_build.outputs.build_config }}
          path: mold/${{ steps.setup_build.outputs.build_config }}.tar.gz

  publish:
    if: github.ref_name == 'main'
    needs: [prepare, build]
    name: Publish build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG_NAME: ${{ needs.prepare.outputs.tag_name }}
    steps:
      - name: Download build outputs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: mold-*
          path: mold/
          merge-multiple: true

      - name: Get versions
        id: get_versions
        env:
          MOLD_STABLE_VERSION: ${{ needs.prepare.outputs.mold_stable_version }}
          MOLD_NIGHTLY_VERSION: ${{ needs.prepare.outputs.mold_nightly_version }}
        run: |
          stable_build="mold-$MOLD_STABLE_VERSION-x86_64-linux"
          tar -xzf "mold/$stable_build.tar.gz"
          mold_stable_version_string="$("$stable_build/bin/mold" -v)"

          nightly_build="mold-$MOLD_NIGHTLY_VERSION-x86_64-linux"
          tar -xzf "mold/$nightly_build.tar.gz"
          mold_nightly_version_string="$("$nightly_build/bin/mold" -v)"

          {
            echo "mold_stable_version_string=$mold_stable_version_string"
            echo "mold_nightly_version_string=$mold_nightly_version_string"
          } | tee -a "$GITHUB_OUTPUT"

      - name: Compute checksums
        id: compute_checksums
        run: |
          cd mold
          sha256sum mold*.tar.gz | tee SHA256SUMS
          {
            echo "sha256sums<<EOF"
            cat SHA256SUMS
            echo "EOF"
          } | tee -a "$GITHUB_OUTPUT"

      - name: Generate release notes
        id: release_notes
        env:
          MOLD_STABLE_VERSION_STRING: ${{ steps.get_versions.outputs.mold_stable_version_string }}
          MOLD_NIGHTLY_VERSION_STRING: ${{ steps.get_versions.outputs.mold_nightly_version_string }}
          SHA256SUMS: ${{ steps.compute_checksums.outputs.sha256sums }}
        run: |
          release_title="mold nightly builds $TAG_NAME"
          notes_file="release-notes.md"
          cat <<EOF | tee -a "$notes_file"
          Stable: \`$MOLD_STABLE_VERSION_STRING\`

          Nightly: \`$MOLD_NIGHTLY_VERSION_STRING\`

          SHA-256 checksums:
          \`\`\`
          $SHA256SUMS
          \`\`\`

          EOF
          {
            echo "release_title=$release_title"
            echo "notes_file=$notes_file"
          } | tee -a "$GITHUB_OUTPUT"

      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TITLE: ${{ steps.release_notes.outputs.release_title }}
          NOTES_FILE: ${{ steps.release_notes.outputs.notes_file }}
        run: |
          gh release create \
            --repo="$GITHUB_REPOSITORY" \
            --title="$RELEASE_TITLE" \
            --notes-file="$NOTES_FILE" \
            --latest \
            "$TAG_NAME" \
            mold/mold*.tar.gz \
            mold/SHA256SUMS
